# Site settings  配置文件信息，在此定义变量，然后使用到各个页面当中，jekyll语法
title: FOXaaFOX'blog
email: zhangyueaijia@qq.com
description: > # this means to ignore newlines until "baseurl:"
  "FOXaaFOX"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://foxaafox.github.io/" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
my-img: 'https://od8kqa01w.bkt.clouddn.com/me.JPG'
weibo:  'https://weibo.com/u/2698725032'
toemail: 'https://mail.qq.com/'
# Social account
# twitter:  username
# weibo:    ID
github: FOXaaFOX
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
