# Site settings
title: FOXaaFOX'blog
email: zhangyueaijia@qq.com
description: > # this means to ignore newlines until "baseurl:"
  "FOXaaFOX"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://foxaafox.github.io/" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'
my-img: 'http://od8kqa01w.bkt.clouddn.com/me.JPG'

# Social account
# twitter:  username
# weibo:    ID
# github:   username
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
